### ISSUE TITLE
Code Review for Problem 4: Add dynamic switching of the views

### ISSUE THREAD

**Issue by Djis247** [Djis247/p4#16]
Summary

The task requires creating a p4.html and a corresponding JSX file p4.jsx that includes both view components (Example and States). The p4.jsx file should implement dynamic switching between the display of the two components using a button.
Feedback

1. Folder Structure

    It's important to ensure that the folder structure is organized and follows best practices. Make sure that the files are placed in the appropriate directories.

2. p4.html file

    Ensure that p4.html is correctly structured and contains the necessary elements, such as a container div to render the components.

3. p4.jsx file

    Verify that p4.jsx correctly imports the Example and States components.
    Implement dynamic switching logic as specified, ensuring that the button toggles between the two views.

4. Webpack Configuration (webpack.config.js)

    Make sure to update webpack.config.js to build the compiled/p4.bundle.js file as specified.
    Verify that the configuration is correctly set up to bundle the necessary files.

5. Error Handling

    Implement error handling for edge cases, such as checking if the components are imported correctly and if the button click event is handled appropriately.

6. Code Quality

    Ensure that the code is well-organized, follows consistent naming conventions, and is easy to read.
    Consider adding comments to explain complex logic or functionality.

7. Documentation

    Provide clear and concise instructions or comments within the code to help other developers understand the purpose and functionality of each file.

8. Readability and Maintainability

    Consider breaking down complex logic into smaller, more manageable functions or components for better readability and maintainability.

**Comment by Cmichau11** [comment]
Problem 4 files implemented in a efficient manner and contains all necessary elements.
Errors not present in the code while changes being added all work as intended.
Documents are readable and if any bugs occur can be changed at a moments notice.
