### ISSUE TITLE
Problem 3: Personalizing the Layout

### ISSUE THREAD

**Issue by Djis247** [Djis247/p4#3]
## Problem 3: Personalizing the Layout

Create a ReactJS component named `Header` that will display a personalized header at the top of a view. Add this header to all ReactJS web apps in your assignment (`gettingStarted.jsx`, `p2.jsx`, `p4.jsx`, `p5.jsx`). Note that you **should not** replace the section from part 1 (your name and motto). That section should be separate from your header. Use your imagination and creativity to create a header that is "uniquely you". This can include additional images, graphics, whatever you like. You can extend the JSX/JavaScript in the components but you may not use external ReactJS Components or JavaScript libraries such as JQuery. Be creative! A colored rectangle with plain text is not sufficient.

The files you will need to implement are:

- `components/header/Header.jsx` - The ReactJS Component of your header component. This is defined as a class Header of type [React.Component](https://reactjs.org/docs/react-component.html).
- `components/header/Header.css` - Any CSS styles your component needs. **You must include some styling for your header here**.

**Comment by dsprad99** [comment]
As a programmer I would like to add a background color to my header.

**Comment by dsprad99** [comment]
As a programmer I would like to add an underline to my text.

**Comment by dsprad99** [comment]
Header completed
