### ISSUE TITLE
Problem 4: Add dynamic switching of the views

### ISSUE THREAD

**Issue by Djis247** [Djis247/p4#4]
## Problem 4: Add dynamic switching of the views

Create a `p4.html` and a corresponding JSX file `p4.jsx` that includes both view components (the `Example` and `States` components). The `p4.jsx` needs to implement an ability to switch between the display of the two components. When a view is displayed there should be a button above it that switches to display the other view. For example, when the `States` view is displayed the button above it should read "Switch to Example," and when pushed the `States` should disappear and the `Example` view should be displayed.

For this problem you will need to create the files above as well as modify the webpack configuration file `webpack.config.js` to build a file `compiled/p4.bundle.js` that you can uses in `p4.html` file. Note that if you are using Webpack with the `--watch` flag (i.e. `npm run build:w`), you will need to restart it after changing `webpack.config.js`.

**Comment by Cmichau11** [comment]
Dynamic Switching Confirmed
